#ifndef ARANGODB_MALLOC_WRAPPER_H
#define ARANGODB_MALLOC_WRAPPER_H 1

#include <sys/types.h>

#define JSMALLOC_ATTRIBUTE(s)                 __attribute__((s))

#define JSMALLOC_ATTRIBUTE_NOTHROW            JSMALLOC_ATTRIBUTE(nothrow)
#define JSMALLOC_ATTRIBUTE_MALLOC         
#define JSMALLOC_ATTRIBUTE_ALLOC_SIZE1(a)     JSMALLOC_ATTRIBUTE(alloc_size(a))
#define JSMALLOC_ATTRIBUTE_ALLOC_SIZE2(a, b)  JSMALLOC_ATTRIBUTE(alloc_size(a, b))
#define JSMALLOC_ATTRIBUTE_NONNULL(a)         JSMALLOC_ATTRIBUTE(nonnull(a))
#define JSMALLOC_ATTRIBUTE_UNUSED             JSMALLOC_ATTRIBUTE(__warn_unused_result__)

#ifdef __cplusplus
# define JSMALLOC_CXX_THROW throw()
#else
# define JSMALLOC_CXX_THROW
#endif

#ifdef __cplusplus
extern "C" {
#endif

/// the C library memory management functions we will override

void   JSMALLOC_ATTRIBUTE_NOTHROW *malloc(size_t size) JSMALLOC_CXX_THROW JSMALLOC_ATTRIBUTE_MALLOC JSMALLOC_ATTRIBUTE_ALLOC_SIZE1(1) JSMALLOC_ATTRIBUTE_UNUSED;
void   JSMALLOC_ATTRIBUTE_NOTHROW *calloc(size_t nmemb, size_t size) JSMALLOC_CXX_THROW JSMALLOC_ATTRIBUTE_MALLOC JSMALLOC_ATTRIBUTE_ALLOC_SIZE2(1, 2) JSMALLOC_ATTRIBUTE_UNUSED;
void   JSMALLOC_ATTRIBUTE_NOTHROW free(void* ptr) JSMALLOC_CXX_THROW;
void   JSMALLOC_ATTRIBUTE_NOTHROW *realloc(void* ptr, size_t size) JSMALLOC_CXX_THROW JSMALLOC_ATTRIBUTE_ALLOC_SIZE1(2) JSMALLOC_ATTRIBUTE_UNUSED;
int    JSMALLOC_ATTRIBUTE_NOTHROW posix_memalign(void** memptr, size_t alignment, size_t size) JSMALLOC_CXX_THROW JSMALLOC_ATTRIBUTE_NONNULL(1);
void   JSMALLOC_ATTRIBUTE_NOTHROW *aligned_alloc(size_t alignment, size_t size) JSMALLOC_CXX_THROW JSMALLOC_ATTRIBUTE_MALLOC JSMALLOC_ATTRIBUTE_ALLOC_SIZE1(2);
void   JSMALLOC_ATTRIBUTE_NOTHROW *memalign(size_t alignment, size_t size) JSMALLOC_CXX_THROW JSMALLOC_ATTRIBUTE_MALLOC;
void   JSMALLOC_ATTRIBUTE_NOTHROW *valloc(size_t size) JSMALLOC_CXX_THROW JSMALLOC_ATTRIBUTE_MALLOC JSMALLOC_ATTRIBUTE_ALLOC_SIZE1(1) JSMALLOC_ATTRIBUTE_UNUSED;
size_t JSMALLOC_ATTRIBUTE_NOTHROW malloc_usable_size(void* ptr) JSMALLOC_CXX_THROW;
int    JSMALLOC_ATTRIBUTE_NOTHROW malloc_trim(size_t pad) JSMALLOC_CXX_THROW;

#ifdef __cplusplus
}
#endif

#endif
